INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('11pistou','8870','België','BE',72.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('11qa','64057','Verenigde Staten','US',98.6)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('1234jackkirby','BH189HT','Verenigd Koninkrijk','GB',99.9)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('123dredge','IP117HR','Verenigd Koninkrijk','GB',89.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('126thst','08854','Verenigde Staten','US',93.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('12magi','8954','België','BE',75.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('1302_vlaanderen','1654','België','BE',63.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('1880wk','04932','Duitsland','DE',99.8)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('1stopbabystore','','Verenigd Koninkrijk','GB',99.6)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('2010montresor','20100','Italië','IT',98.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('2013beauty13','','Duitsland','DE',99.7)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('2013pinkfriday','9190','België','BE',99.1)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('24musiclady','NG43ND','Verenigd Koninkrijk','GB',59.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('26ruedulabrador','5002','België','BE',97.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('5mcd','SE129AN','Verenigd Koninkrijk','GB',78.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('643doubleplaycards2010','PE27BW','Verenigd Koninkrijk','GB',93.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('64basque','','Frankrijk','FR',61.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('67richard','3435DW','Nederland','NL',56.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('69boomer','13350','Verenigde Staten','US',94.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('7379bob','1650','België','BE',97.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('a_davy','3730','België','BE',66.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('abeldoorn','3930','Woudenberg,Nederland','NL',67.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('absolutecomicsandstatues','11374','Verenigde Staten','US',99.8)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('actualcoolcats','23235','Verenigde Staten','US',99.6)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('adamsworldnl','7245AX','Nederland','NL',99.9)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('adcollection','5025AC','Nederland','NL',98.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('adidassambatrainers','BN99PN','Verenigd Koninkrijk','GB',68.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('admul','5624CA','Nederland','NL',75.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('afeefa80','LS83QW','Verenigd Koninkrijk','GB',98.2)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('agrios-buch','51427','Duitsland','DE',99.9)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('aherolegacycomics','06040','Verenigde Staten','US',99.6)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('albalk97','01420','Verenigde Staten','US',83.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('alexthefatdawg','SA488AE','Verenigd Koninkrijk','GB',99.8)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('ali19550','4822','Oostenrijk','AT',78.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('alsaret$genny99','05036','Italië','IT',99.5)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('alternateuniversecomics','SL99DH','Verenigd Koninkrijk','GB',100.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('alterverse','06511','Verenigde Staten','US',66.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('ann_cloughton','YO130AT','Verenigd Koninkrijk','GB',74.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('anne-clara','2500','België','BE',91.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('annemanieke','1910','België','BE',90.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('annh1559','2100','België','BE',96.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('anniea123','HX26AJ','Verenigd Koninkrijk','GB',69.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('anticousato','70122','Italië','IT',78.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('antikspielzeug','55127','Duitsland','DE',99.9)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('antiktharandt09','01737','Duitsland','DE',99.7)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('antiquariat_dr.lautwein','90489','Duitsland','DE',99.8)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('antique.secondhandshop','','België','BE',78.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('antiqueprintsandmaps_nl','6581WP','Nederland','NL',99.1)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('aphebe','','Frankrijk','FR',61.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('a-place-in-space','CR01RN','Verenigd Koninkrijk','GB',87.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('archivecomics','32780','Verenigde Staten','US',56.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('argie_de','','Duitsland','DE',83.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('arkle3','','Verenigd Koninkrijk','GB',64.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('arsenicjulie','31634','Duitsland','DE',64.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('art.and.books','10043','Italië','IT',99.8)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('assofreeciak','10141','Italië','IT',99.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('astainvista04','','Italië','IT',99.6)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('a-toys','56154','Duitsland','DE',97.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('auctionbargainshere','11001','Verenigde Staten','US',99.9)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('avaz2838','76549','Verenigde Staten','US',61.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('balak_nl','1094SM','Nederland','NL',80.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('bampf-collectables','BS148NF','Verenigd Koninkrijk','GB',90.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('bargain$eeker','16412','Verenigde Staten','US',80.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('baronselderie-62','46499','Duitsland','DE',86.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('bazardellibro','73100','Italië','IT',99.5)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('beatchapter','E70NJ','Verenigd Koninkrijk','GB',87.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('beautyzz2009','','Verenigd Koninkrijk','GB',98.9)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('beerzshop','2152TG','Nederland','NL',95.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('belgian-coast','8560','België','BE',58.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('bellashop05','45768','Duitsland','DE',88.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('beloved-max','6041JR','Nederland','NL',96.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('ben1955_nl','','Nederland','NL',75.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('berwannes','8000','België','BE',90.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('betelgese','','Italië','IT',56.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('bianchi99','5076','Haaren,Nederland','NL',0.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('bildertraum','','Duitsland','DE',99.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('bisjeke','9320','België','BE',87.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('blarte','47100','Italië','IT',99.6)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('blas2283','','Verenigd Koninkrijk','GB',99.8)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('blastfromthepastmagazine','PE28HF','Verenigd Koninkrijk','GB',57.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('blaswell','','Nederland','NL',88.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('bluronin85','','Italië','IT',99.7)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('bobbybutt11','MK464DR','Verenigd Koninkrijk','GB',99.9)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('bobcrocker','02879','Verenigde Staten','US',64.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('bobsco64','PR83DQ','Verenigd Koninkrijk','GB',94.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('boekenband','8200','België','BE',58.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('boekenwormpje','4014PW','Nederland','NL',78.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('bombero47','9050','België','BE',95.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('bongkong','97211','Verenigde Staten','US',86.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('books_discount','PR98QH','Verenigd Koninkrijk','GB',99.6)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('boondockcollectibles','11767','Verenigde Staten','US',99.9)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('boonsart','2515BA','Nederland','NL',99.9)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('boubou1713','7100','België','BE',99.3)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('breezer-man','77880','Duitsland','DE',96.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('brocantique-30','30250','Frankrijk','FR',81.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('buch24-de','','Duitsland','DE',69.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('buch-service-2.hand','70378','Duitsland','DE',99.9)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('buchweltonline','24539','Duitsland','DE',99.9)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('bulb_inc','93550','Verenigde Staten','US',96.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('buntespapier_de','47057','Duitsland','DE',86.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('buy','','Verenigde Staten','US',99.3)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('calpix','','Verenigde Staten','US',61.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('capitalmale','22046','Verenigde Staten','US',99.6)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('ccsims02','CF481DB','Verenigd Koninkrijk','GB',99.8)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('cercachetrovi99','48100','Italië','IT',99.2)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('champ0814','9690','België','BE',82.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('charles1076','EX25DU','Verenigd Koninkrijk','GB',99.8)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('chealton','90766','Duitsland','DE',95.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('checkpoint45','SK66GD','Verenigd Koninkrijk','GB',99.9)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('chikira','','Nederland','NL',100.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('chipmunk5178','','Nederland','NL',95.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('chlp1815','','Verenigd Koninkrijk','GB',64.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('chrisdmbebis','1480','België','BE',69.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('christian6760','6724','België','BE',99.8)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('chunkaay','90020','Verenigde Staten','US',56.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('ciadlo','','Mexico','MX',70.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('clioheist','2220','België','BE',96.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('cmbooksnstuff','75063','Verenigde Staten','US',99.5)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('cocacolafanta','70825','Duitsland','DE',99.4)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('coco3766','6000','België','BE',99.8)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('cocoyovanny888','01259','Duitsland','DE',99.9)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('codingknuffel','9320','België','BE',92.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('coldtonnageman','GU206JQ','Verenigd Koninkrijk','GB',90.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('collectorsdenwf','76306','Verenigde Staten','US',99.6)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('collectorshop24nl','3565AV','Nederland','NL',64.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('collectorsworld-va','22003','Verenigde Staten','US',99.9)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('collectoushop','49360','Frankrijk','FR',99.7)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('comic.productions.nordbaden','77855','Duitsland','DE',62.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('comic.sense','11710','Verenigde Staten','US',92.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('comic_collector1974','20782','Verenigde Staten','US',71.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('comic_haus','44135','Duitsland','DE',57.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('comicanderl','81929','Duitsland','DE',58.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('comic-biz-store','N129LH','Verenigd Koninkrijk','GB',81.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('comic-kontor-no.1','69151','Duitsland','DE',79.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('comicladen-kollektiv','20259','Duitsland','DE',56.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('comiclick','','Duitsland','DE',58.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('comicmania101','S118JG','Verenigd Koninkrijk','GB',86.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('comixzoneonline','13212','Verenigde Staten','US',99.9)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('conventionex','33016','Verenigde Staten','US',99.8)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('cookee-bookee','N33AE','Verenigd Koninkrijk','GB',57.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('corur','6641','Beuningen GLD,Nederland','NL',77.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('cosmicdiarist','M15QD','Verenigd Koninkrijk','GB',58.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('cosmicgiftsuk','YO152DS','Verenigd Koninkrijk','GB',99.8)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('cottage_of_lost_play','2610','België','BE',81.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('crocobio','1400','België','BE',85.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('crystalshift','11208','Verenigde Staten','US',99.2)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('culturalexperience27','15610','Verenigde Staten','US',94.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('curefan17','89015','Verenigde Staten','US',94.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('dabro4711','3191','Hoogvliet Rotterdam,Nederland','NL',100.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('daleyinternational2012','E153BP','Verenigd Koninkrijk','GB',89.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('dangio_max','40139','Italië','IT',98.8)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('dannygemma','SW24LB','Verenigd Koninkrijk','GB',88.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('davidemensch','5707XZ','Nederland','NL',0.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('daywarm000','TS14JF','Verenigd Koninkrijk','GB',99.4)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('dddavids777','97401','Verenigde Staten','US',99.9)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('ddkcarl','2170','België','BE',98.9)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('dead.peoples.stuff','95376','Verenigde Staten','US',67.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('deardidi','9032','België','BE',98.9)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('debali','11552','Verenigde Staten','US',98.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('debelder73','2570','België','BE',71.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('deceaseddog','GY11HY','Verenigd Koninkrijk','GB',100.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('deepspaceeleven','','Verenigd Koninkrijk','GB',97.6)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('dejowi','79280','Duitsland','DE',99.9)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('dekker84','2587HM','Nederland','NL',72.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('demonciccio','17024','Italië','IT',99.9)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('devizescollectables','SN102JR','Verenigd Koninkrijk','GB',99.9)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('diacaras','7559CP','Nederland','NL',57.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('dieterscomic','73732','Duitsland','DE',66.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('dildoke','3000','België','BE',91.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('dirtyharry0162','72574','Duitsland','DE',97.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('dishgo','7522CS','Nederland','NL',0.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('dituttopertutti.mercatino','38050','Italië','IT',99.5)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('dizneyart','98611','Verenigde Staten','US',98.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('dlddestock62','62750','Frankrijk','FR',99.7)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('doctorbooksrl','61100','Italië','IT',99.6)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('dominique9756','8950','België','BE',96.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('doroteo74','06016','Italië','IT',99.9)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('dove-shop','HU70YF','Verenigd Koninkrijk','GB',99.9)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('drsox2036','8000','België','BE',92.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('dr-wazoo','33316','Verenigde Staten','US',98.3)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('dtacoll','33618','Verenigde Staten','US',99.8)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('duckburg','','Duitsland','DE',63.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('dustmop45','97365','Verenigde Staten','US',78.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('easy-ankauf','24113','Duitsland','DE',99.9)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('editions_du_jeudi','4020','België','BE',74.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('eer323','1653','België','BE',60.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('ejgleb','','Nederland','NL',56.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('eklo2002','35394','Duitsland','DE',85.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('elenarossetti1975','82018','Italië','IT',98.4)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('elric3007','TQ121YB','Verenigd Koninkrijk','GB',70.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('encanledo','38259','Duitsland','DE',99.6)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('endrucomics','','Italië','IT',58.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('eufrazie','9280','België','BE',86.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('euram','','België','BE',96.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('european-grading-service','53894','Duitsland','DE',88.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('euroverzend','5611','Eindhoven,Nederland','NL',99.6)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('eurus2000','','Duitsland','DE',56.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('everything-football','','Verenigd Koninkrijk','GB',99.8)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('faetigigliola62','47035','Italië','IT',80.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('fannynanou','1050','België','BE',93.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('fantasia-spielzeug.de','14050','Duitsland','DE',99.8)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('fantasticstore','38118','Duitsland','DE',99.9)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('fantasy-comics','10526','Verenigde Staten','US',60.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('fc089081','4920','België','BE',91.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('fcdisie','1767CM','Nederland','NL',79.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('fede1673','37060','Italië','IT',99.8)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('feldec68','84025','Italië','IT',99.9)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('ferifox27','00172','Italië','IT',99.9)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('fifer_andy','KY62PT','Verenigd Koninkrijk','GB',83.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('figo_de_kat','2600','België','BE',70.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('filip9900','','België','BE',62.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('filtheforce','8800','België','BE',90.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('fiodor72','','Italië','IT',99.9)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('firefly1685','03062','Verenigde Staten','US',74.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('f-l-o-h-1-0-0','85221','Duitsland','DE',93.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('florent1935','9990','België','BE',57.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('flyingcloggie','5301ZX','Nederland','NL',92.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('fonorama','3520','België','BE',63.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('fourguysandachick','28625','Verenigde Staten','US',99.9)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('francesco-alberti','10117','Duitsland','DE',99.6)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('frankieoost','7543DJ','Nederland','NL',62.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('franklin6060','','Duitsland','DE',78.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('frankloos2008','3680','België','BE',89.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('fredgales','1052RR','Nederland','NL',80.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('fromthevault2u','13027','Verenigde Staten','US',99.8)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('fruitylicious_uk','WA117AG','Verenigd Koninkrijk','GB',80.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('fun2sport','2573','''s-Gravenhage,Nederland','NL',75.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('funzonexxl','3272','België','BE',82.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('gadgetfreaknl','6411NC','Nederland','NL',76.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('gameveen','1013BZ','Nederland','NL',0.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('garry_creations','','Verenigd Koninkrijk','GB',63.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('gebr.-kuehn-fachhandel-buecher-spielwaren-bastelbedarf','57319','Duitsland','DE',77.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('geelgroen1234','9340','België','BE',87.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('geitestaart','7880','België','BE',94.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('geluidsdragers','7831HA','Nederland','NL',99.9)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('geoconde','8400','België','BE',88.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('george.l','PL67EQ','Verenigd Koninkrijk','GB',74.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('ggmont','50300','Frankrijk','FR',99.5)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('gieken0','2000','België','BE',62.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('glunderw0rld','','Nederland','NL',96.7)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('goldrhox','9034HG','Nederland','NL',61.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('good-old-antiques','1980','België','BE',88.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('gorgias62','2492NP','Nederland','NL',100.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('gr273','','Nederland','NL',67.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('gravin99','6372KD','Nederland','NL',96.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('greendiamonds1','3010','België','BE',73.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('grethescraftartandwool','CT102JS','Verenigd Koninkrijk','GB',99.8)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('griffioengrafiek','','Nederland','NL',80.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('gruttosi','2496HX','Nederland','NL',95.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('guardion','70327','Duitsland','DE',82.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('gugumed_it','06126','Italië','IT',99.7)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('h2comics','6531KC','Nederland','NL',93.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('hajogeur','4824JJ','Nederland','NL',99.7)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('hajomaje','84037','Verenigde Staten','US',70.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('hallofjusticecomics','80138','Verenigde Staten','US',87.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('hamsterklf76','LS73ET','Verenigd Koninkrijk','GB',57.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('hannah11zoe','BS217TG','Verenigd Koninkrijk','GB',99.8)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('hans511126johannes','2726TJ','Nederland','NL',99.7)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('hans6075','ST72HX','Verenigd Koninkrijk','GB',98.2)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('hansboeken13','1357PR','Nederland','NL',80.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('happys-comic-marktplatz','42799','Duitsland','DE',99.9)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('harleyscomics','M146AU','Verenigd Koninkrijk','GB',91.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('haveanicedaytoday','1601JP','Nederland','NL',67.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('hawthornstrading','NR67EQ','Verenigd Koninkrijk','GB',99.9)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('hecomic','93053','Duitsland','DE',99.7)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('hemiagnos','1120','België','BE',96.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('henk1230','','Nederland','NL',88.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('hero4sale','10999','Duitsland','DE',56.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('herobincollectables','33071','Verenigde Staten','US',79.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('hevanba','5012AE','Nederland','NL',80.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('hh-automobilia','45964','Duitsland','DE',96.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('hobbyruimte','8300','België','BE',94.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('horio-be2014','1170','België','BE',62.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('hospiz-spendenverkauf','45661','Duitsland','DE',56.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('house_of_stamps_67','67150','Frankrijk','FR',98.6)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('hovebooks','BN37SB','Verenigd Koninkrijk','GB',57.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('i.fratt.1972','00041','Italië','IT',99.8)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('iamnotwolverine','S207LR','Verenigd Koninkrijk','GB',56.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('ichartasrl','','Italië','IT',77.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('indyjones9793','98506','Verenigde Staten','US',60.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('infamous9indy','46221','Verenigde Staten','US',94.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('info-on-collectibles','8560','België','BE',99.8)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('inmondadori','','Italië','IT',99.1)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('jaceshad','04657','Verenigde Staten','US',92.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('jahreb','','Verenigde Staten','US',71.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('jankawasaki','3461HL','Nederland','NL',77.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('janlej','8310','België','BE',95.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('jar_jar__1','','Duitsland','DE',99.6)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('jarod_64','44100','Italië','IT',100.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('jasonbarber24','43228','Verenigde Staten','US',96.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('jbs15','','Verenigde Staten','US',57.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('jeanphih','6990','België','BE',73.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('jeroenvossen','3650','België','BE',84.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('jhquarles','75703','Verenigde Staten','US',61.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('jjmaxistore','47843','Italië','IT',96.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('joca2425','3920','België','BE',65.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('johndanvers','2060','België','BE',56.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('johns-modelcarsandtrains','','Nederland','NL',99.9)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('johnson.girls','55345','Verenigde Staten','US',83.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('jolan59','6700','België','BE',61.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('jonah-hex-lives','BS374AX','Verenigd Koninkrijk','GB',99.8)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('jonbaron','2000','België','BE',98.6)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('joncas45','S358PA','Verenigd Koninkrijk','GB',99.9)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('joske2399','8980','België','BE',75.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('jpjp1999','27012','Verenigde Staten','US',86.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('jp-stamps','6414EH','Nederland','NL',83.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('jven_nl','5258ER','Nederland','NL',66.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('k_en_d_used_items','6446BX','Nederland','NL',96.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('kanakaris1','3630','België','BE',81.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('karnomotorsport','','Frankrijk','FR',98.7)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('katelb0','LE88BH','Verenigd Koninkrijk','GB',84.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('katiehughes262012','S704LX','Verenigd Koninkrijk','GB',99.8)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('kautzcollect','3441XJ','Nederland','NL',59.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('keeslahaze','','Nederland','NL',68.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('kerouacroad','W55NH','Verenigd Koninkrijk','GB',99.9)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('kevinspacey20','73112','Verenigde Staten','US',98.5)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('khazaarh','5640','België','BE',63.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('khovan38','38480','Frankrijk','FR',99.9)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('kilagon10','90504','Verenigde Staten','US',56.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('koeiekop','5953CK','Nederland','NL',83.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('kolmhofer','4070','Oostenrijk','AT',99.4)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('koopveiligonlineshop','3273AC','Nederland','NL',83.3)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('kristpie','3560','België','BE',77.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('kryptonkomics','','Verenigd Koninkrijk','GB',99.9)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('kstudio','43068','Verenigde Staten','US',60.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('kuiftinbob','9200','België','BE',68.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('kulturgutes','64546','Duitsland','DE',60.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('kurtje1972','8670','België','BE',80.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('lacavedaromes','94140','Frankrijk','FR',60.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('lacollezionistamoltocarina65','80100','Italië','IT',93.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('lamo27','4431','België','BE',89.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('lauronadon','07866','Verenigde Staten','US',62.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('laz-e-bid','41001','Verenigde Staten','US',99.4)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('le_grenier_des_bd2011','4020','België','BE',61.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('ledepotliege','4000','België','BE',60.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('lee1913','03054','Verenigde Staten','US',92.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('legras_doritha','5324AX','Nederland','NL',91.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('leopoldc3','9190','België','BE',87.5)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('lethal_quicksilver','94928','Verenigde Staten','US',57.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('librairiehistoiresdarts','35000','Frankrijk','FR',82.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('libreriavitanova','35010','Italië','IT',81.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('libridiireale','40131','Italië','IT',97.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('libromania_matera','75100','Italië','IT',65.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('librosalento','','Italië','IT',90.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('lie12345','2018','België','BE',0.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('lightningbolt1979','7823AC','Nederland','NL',84.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('livresetdesseins','08000','Frankrijk','FR',99.1)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('lo_turco72','80126','Italië','IT',99.6)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('logunnsblade-uk','IG50JB','Verenigd Koninkrijk','GB',76.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('lokov0','06179','Duitsland','DE',63.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('londonreznor','21016','Italië','IT',99.6)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('lospecchiodelrock','95019','Italië','IT',99.7)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('lost4toys','11552','Verenigde Staten','US',87.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('lucantonio2005','80123','Italië','IT',74.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('lucasmart','85600','Frankrijk','FR',99.7)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('lucbert','10064','Italië','IT',61.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('lucien230','20124','Italië','IT',69.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('lucky86_fr','','Frankrijk','FR',80.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('ludofr76','1430','België','BE',66.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('lymbus','65123','Italië','IT',99.9)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('lyubiza','20148','Italië','IT',75.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('m.den.hartog','3707TK','Nederland','NL',81.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('macdui01','','Verenigd Koninkrijk','GB',95.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('macduidigital','EH112AW','Verenigd Koninkrijk','GB',99.3)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('madformags','SK117PG','Verenigd Koninkrijk','GB',99.8)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('mad-mart','YO164RX','Verenigd Koninkrijk','GB',94.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('magazine-machine','','Verenigd Koninkrijk','GB',95.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('magazinemarkt','3553RT','Nederland','NL',98.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('magic_white_unicorn','CF417TT','Verenigd Koninkrijk','GB',72.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('mamadejan','2340','België','BE',98.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('mamy7009','23100','Italië','IT',85.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('manga_book_sales','78613','Verenigde Staten','US',65.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('mangusta086','12073','Italië','IT',99.7)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('marcos_bathroom','IP145UD','Verenigd Koninkrijk','GB',99.6)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('marijka_m','92656','Verenigde Staten','US',90.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('marius0703','2515BG','Nederland','NL',71.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('marrc2','1080','België','BE',98.8)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('martindaglelie','9203ZC','Nederland','NL',85.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('martinridley','N42PQ','Verenigd Koninkrijk','GB',72.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('mary5715','','Verenigd Koninkrijk','GB',62.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('masbrad','95363','Verenigde Staten','US',99.2)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('mavito','10036','Italië','IT',99.9)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('maxigamer_be','2610','België','BE',72.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('mcmom53','5403LB','Nederland','NL',81.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('mekanykal','85008','Verenigde Staten','US',99.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('mericourt0_0','5101','België','BE',72.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('mfholmes27','PE29QA','Verenigd Koninkrijk','GB',99.8)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('midpacific2002','96814','Verenigde Staten','US',65.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('mike-denis','SK145NS','Verenigd Koninkrijk','GB',74.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('mikeshep68','W139DS','Verenigd Koninkrijk','GB',84.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('mimmo.fumetti','72020','Italië','IT',98.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('min3738','CW57GG','Verenigd Koninkrijk','GB',98.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('minneke1972','2500','België','BE',99.5)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('misseypootle','S614NR','Verenigd Koninkrijk','GB',80.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('mktoysandbooks-uk','BT56QR','Verenigd Koninkrijk','GB',82.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('mkunst2012','2000','België','BE',65.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('modder1970','6836PA','Nederland','NL',69.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('modelbouwdon-felipe','2100','België','BE',86.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('mohitojo','SE38TN','Verenigd Koninkrijk','GB',92.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('moneywisebooks','NR303NQ','Verenigd Koninkrijk','GB',99.9)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('mooiweertje22','6882HM','Nederland','NL',75.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('moosewoodson','38116','Verenigde Staten','US',78.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('morti_i','AL60JL','Verenigd Koninkrijk','GB',56.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('mo-schu','83620','Duitsland','DE',99.9)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('msefsathome','HP226HH','Verenigd Koninkrijk','GB',83.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('multitronixx','90134','Italië','IT',99.3)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('musicandbooksetc','','Verenigd Koninkrijk','GB',61.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('musicandmovie-fan-be','','België','BE',92.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('musicsubway.dolf','5527KD','Nederland','NL',99.9)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('mycomicshop','76010','Verenigde Staten','US',99.5)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('neapolis-2008','80038','Italië','IT',99.8)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('newprix','58036','Italië','IT',99.7)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('nielsklinkenberg','7411KR','Nederland','NL',76.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('nitrox1966','','Amerikaans-Samoa','AS',68.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('njfenner','','Verenigd Koninkrijk','GB',99.9)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('nordseekunst','21789','Duitsland','DE',56.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('nostalgie1895','01612','Duitsland','DE',99.8)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('now4sale13','9881','België','BE',73.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('oaktree709','TN62UW','Verenigd Koninkrijk','GB',70.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('oban4me','','België','BE',97.3)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('oh..so','PE134QE','Verenigd Koninkrijk','GB',89.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('ohko','B323RL','Verenigd Koninkrijk','GB',57.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('oldgit1940','','Verenigd Koninkrijk','GB',74.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('oliver_kammler','03149','Duitsland','DE',76.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('olivier9862','03800','Frankrijk','FR',99.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('omepeet','2289ER','Nederland','NL',67.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('online-handel','15370','Duitsland','DE',99.2)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('oodals_uk','60954','Verenigde Staten','US',99.3)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('oodals_us','NR70WF','Verenigd Koninkrijk','GB',99.4)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('origineelgeschenkje','9320','België','BE',88.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('oscars428','','Verenigd Koninkrijk','GB',99.9)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('ouwens4','3114','Schiedam,Nederland','NL',56.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('p4420580','9120','België','BE',64.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('panis_offertissime','','Italië','IT',75.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('papawembandre','7880','België','BE',59.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('paper-and-books','3000','België','BE',75.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('paris-texas04','','Italië','IT',89.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('passieflora3680','3680','België','BE',96.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('patbateman43','11374','Verenigde Staten','US',60.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('patti2000','','Duitsland','DE',99.9)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('pcarena-bristol','','Verenigd Koninkrijk','GB',99.6)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('peachke','2235','België','BE',70.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('penfold_t_mole','NG36EJ','Verenigd Koninkrijk','GB',77.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('petesiboy','33467','Verenigde Staten','US',60.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('petfred87','8500','België','BE',71.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('phil666732','4032','België','BE',67.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('piedra1963','','Italië','IT',99.9)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('pjsautolit','50669','Verenigde Staten','US',99.9)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('pkgsales','95136','Verenigde Staten','US',90.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('placeagora','45290','Frankrijk','FR',99.6)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('planet-media','76887','Duitsland','DE',99.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('platinum1400','94127','Verenigde Staten','US',64.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('pops_comics','72034','Verenigde Staten','US',66.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('postyzd','8630','België','BE',94.1)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('power-flame','','Duitsland','DE',73.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('ppateb','','Duitsland','DE',83.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('prairie.partners','47436','Verenigde Staten','US',87.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('punk_rock_addict','04133','Polen','PL',59.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('quanha-boy','3920','België','BE',87.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('queenrocks64','4566AN','Nederland','NL',76.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('qujav','30735','Verenigde Staten','US',99.8)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('racingracoon','SN252EB','Verenigd Koninkrijk','GB',82.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('ramopen66','90419','Duitsland','DE',99.9)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('random.cool.stuff','N165RB','Verenigd Koninkrijk','GB',71.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('rare_records09','1730','België','BE',70.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('rascozion','9280','België','BE',94.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('ratbike_nl','','Nederland','NL',99.9)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('redhotcomics','G459UH','Verenigd Koninkrijk','GB',71.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('reinerschuckmonstersandheroes','64289','Duitsland','DE',90.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('remi11_nl','2317','Leiden,Nederland','NL',67.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('replayvideogames_co_uk','WR144NG','Verenigd Koninkrijk','GB',99.9)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('resbook','90143','Italië','IT',99.9)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('rgilbert15','14304','Verenigde Staten','US',99.6)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('rhand09','9686VE','Nederland','NL',81.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('ridderhenck','7943CP','Nederland','NL',90.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('ridersco.shop','BD24JP','Verenigd Koninkrijk','GB',99.7)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('rik550s','PE71QA','Verenigd Koninkrijk','GB',99.9)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('rilela','23611','Duitsland','DE',86.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('ritasclearencesale','6412SP','Nederland','NL',69.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('rlbaines','S57SN','Verenigd Koninkrijk','GB',96.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('road0476','9700','België','BE',66.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('robbieyee','27613','Verenigde Staten','US',68.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('robertr3293','20110','Verenigde Staten','US',75.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('robsnka','8052','Oostenrijk','AT',69.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('rockdude1','86413','Verenigde Staten','US',99.5)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('rockitman2691','5854BS','Nederland','NL',88.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('rogedi','','Nederland','NL',69.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('rossana1174','24050','Italië','IT',99.8)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('rotterdam_comics','3071VH','Nederland','NL',68.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('rubikcubelife','','Verenigd Koninkrijk','GB',98.1)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('ruttimm','1053KP','Nederland','NL',0.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('ruudoverdijk','1328ES','Nederland','NL',61.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('ryzard_nl','9713GW','Nederland','NL',98.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('sailyawa','18643','Verenigde Staten','US',99.1)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('salem3.5.7','13006','Frankrijk','FR',97.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('samisassy','','Verenigde Staten','US',98.9)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('sandeling_nl','3342GC','Nederland','NL',99.6)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('sandgate1953','LS257EY','Verenigd Koninkrijk','GB',70.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('sandygilchristworld','','Verenigd Koninkrijk','GB',88.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('sanmar-2008','1025TM','Nederland','NL',59.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('santeclaus','','Verenigd Koninkrijk','GB',99.9)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('sas1athome71','60148','Verenigde Staten','US',99.5)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('satiropa','2300','België','BE',93.1)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('sauliusst','DA144AA','Verenigd Koninkrijk','GB',99.7)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('schaumburger-shop','31688','Duitsland','DE',99.9)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('selling_great_items','34787','Verenigde Staten','US',62.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('serependiteit','','België','BE',85.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('serpentina_nl','','Nederland','NL',66.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('sewbeck','CV325YF','Verenigd Koninkrijk','GB',99.6)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('shancq184','1450','België','BE',90.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('shellheadcomics2','63125','Verenigde Staten','US',57.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('sia-sarahshop','4116CH','Nederland','NL',63.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('silmarilrp12','63100','Italië','IT',99.8)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('silverspaceknight','37188','Verenigde Staten','US',89.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('simiansalesinc','50265','Verenigde Staten','US',99.9)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('sirioja96','16200','Frankrijk','FR',99.9)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('siwime','4824','Breda,Nederland','NL',89.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('sk-bookscom','','Verenigd Koninkrijk','GB',58.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('skepora','2220','België','BE',85.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('smoeltje0','6845KE','Nederland','NL',73.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('snapelio','24040','Italië','IT',99.8)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('sockeyedavid','99615','Verenigde Staten','US',92.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('sof1967','45200','Frankrijk','FR',84.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('soncla34','34290','Frankrijk','FR',99.6)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('spaansespook','5283','Boxtel,Nederland','NL',99.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('speedy-jay','HA51DB','Verenigd Koninkrijk','GB',83.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('spendi_spandi_effendi','80132','Italië','IT',79.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('sportwagen0807','9870','België','BE',77.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('spots1412','1057HJ','Nederland','NL',0.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('sprintkonijn','9100','België','BE',99.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('stakstik1','9300','België','BE',99.9)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('staplerremover','','Verenigd Koninkrijk','GB',84.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('steve_robbi','37083','Duitsland','DE',69.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('steveh974','BR31TY','Verenigd Koninkrijk','GB',99.9)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('stew1974','15317','Verenigde Staten','US',99.6)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('stone_soup_records','LL186HA','Verenigd Koninkrijk','GB',56.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('stopinette061','6890','België','BE',85.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('stouf70','70120','Frankrijk','FR',88.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('sugie30','8310','België','BE',99.8)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('superboy632','16509','Verenigde Staten','US',59.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('super-buch','51469','Duitsland','DE',99.8)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('suswis','4273XA','Nederland','NL',83.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('suzie_c','TW26NQ','Verenigd Koninkrijk','GB',86.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('suzys_magazines_and_comics','RG127FG','Verenigd Koninkrijk','GB',71.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('swordt2000','08820','Verenigde Staten','US',74.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('sycamorebooks','WN58HB','Verenigd Koninkrijk','GB',99.9)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('takesuback4vinyl','SK117YW','Verenigd Koninkrijk','GB',99.9)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('tanjae2255','36039','Duitsland','DE',99.7)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('tanmanandlex','59602','Verenigde Staten','US',99.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('tantys','2235','België','BE',67.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('tastevin-be','1050','België','BE',98.8)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('t-bucket777','37724','Verenigde Staten','US',76.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('tchang5','4651','België','BE',98.9)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('tellybox','LA14TH','Verenigd Koninkrijk','GB',64.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('teusvc','3527WG','Nederland','NL',0.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('thbargains2012','HP12PJ','Verenigd Koninkrijk','GB',98.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('theatticbug','','Verenigd Koninkrijk','GB',99.9)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('thecargohold','','Verenigde Staten','US',76.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('thecomicnewsstand','19066','Verenigde Staten','US',99.9)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('thedrewcarson','EH269BB','Verenigd Koninkrijk','GB',86.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('thegreatgearstore','','Verenigd Koninkrijk','GB',99.7)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('thejumpingfrog','','Verenigde Staten','US',99.6)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('thelistedliss','M2R2S9','Canada','CA',70.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('thesuperbikebarn2012','7242CH','Nederland','NL',91.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('thethreeneils222','CO102YW','Verenigd Koninkrijk','GB',76.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('the-white-tiger001','7100','België','BE',66.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('they_walk_among_us','TW91RW','Verenigd Koninkrijk','GB',77.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('think-magazines-uk','EX226PS','Verenigd Koninkrijk','GB',70.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('thomasdenies','4331HN','Nederland','NL',0.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('times-were-when','','Nederland','NL',80.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('timmy--2000','1181NV','Nederland','NL',94.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('titileterrible','J0K1S0','Canada','CA',93.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('tragopaan','2930','België','BE',94.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('trickyal77','DE224JQ','Verenigd Koninkrijk','GB',93.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('tripje_nl','','Nederland','NL',63.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('twinspappalardo2011','','Italië','IT',99.8)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('uanta15','','Verenigd Koninkrijk','GB',96.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('ube108ube','43100','Italië','IT',82.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('umberto8951','81025','Italië','IT',99.7)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('uniformuniverse','BB97UT','Verenigd Koninkrijk','GB',99.6)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('univista!','HA96EA','Verenigd Koninkrijk','GB',68.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('upidana','31515','Duitsland','DE',99.6)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('us2014.topl','97055','Verenigde Staten','US',85.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('vanni.c','20060','Italië','IT',58.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('vassyv','26300','Frankrijk','FR',99.5)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('velboyz','PL51AU','Verenigd Koninkrijk','GB',65.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('vian12','3300','België','BE',97.8)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('victorycomicsgroup','22046','Verenigde Staten','US',99.9)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('vincer2005','5611PR','Nederland','NL',84.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('vintagedecoration','3210','België','BE',0.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('vintageitemcom','9700','België','BE',99.8)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('vintagexplosion','','Nederland','NL',77.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('vinylon','84166','Duitsland','DE',99.9)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('viper152','7863','België','BE',61.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('vlaamsstripcentrum','2610','België','BE',74.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('voenkie','3271','België','BE',56.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('w.bakker','3051LN','Nederland','NL',57.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('warhorse1967','71302','Verenigde Staten','US',99.8)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('watermill_books','SA183GY','Verenigd Koninkrijk','GB',99.8)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('waterwoman54','2592VG','Nederland','NL',74.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('wedding.24july2010','B146DE','Verenigd Koninkrijk','GB',59.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('wem48','1780','België','BE',65.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('werni2','16727','Duitsland','DE',75.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('whisperingchicken','CV345QN','Verenigd Koninkrijk','GB',66.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('wisco82kpm','91403','Verenigde Staten','US',64.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('witteoctopus','8310','België','BE',83.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('wizona-nl','','Nederland','NL',65.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('wormke-grutman','1851','België','BE',79.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('wrathofmdfmk','95340','Verenigde Staten','US',99.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('wvd-verzamelen1','3328TG','Nederland','NL',93.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('www_lopo24_de','68766','Duitsland','DE',99.5)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('xray_37','3200','België','BE',94.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('xujinglei1688','','China','CN',99.8)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('xxcharlezxx','34112','Verenigde Staten','US',95.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('yankees508phillies','17050','Verenigde Staten','US',99.5)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('yardsaleholland','5022BE','Nederland','NL',93.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('yasminannabelle89','','Verenigd Koninkrijk','GB',84.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('you*mag','','Italië','IT',95.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('yourbusiness2012','','Hongkong','HK',91.2)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('zap3000','3212','België','BE',84.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('zeldatetris','33155','Verenigde Staten','US',78.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('zombiepie23','PL267QX','Verenigd Koninkrijk','GB',70.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('zursammlereckeba','96050','Duitsland','DE',99.9)