INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('((marion))','2691','''s-Gravenzande,Nederland','NL',72.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('*caveat_emptor*','78467','Duitsland','DE',58.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('*mortis*','WA35EA','Verenigd Koninkrijk','GB',80.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('*tic-tac-toys*','','Duitsland','DE',80.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('01goldkrone','01156','Duitsland','DE',99.7)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('110123margaret','OX129PX','Verenigd Koninkrijk','GB',58.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('123gutedinge','51789','Duitsland','DE',99.9)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('1ahandelspartner','45527','Duitsland','DE',94.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('1stcorps','DN149JN','Verenigd Koninkrijk','GB',90.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('2007cecilev','2400','België','BE',96.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('2007rutger','2402BW','Nederland','NL',76.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('2010toddie70','22117','Duitsland','DE',87.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('20greenfingers','SO211PE','Verenigd Koninkrijk','GB',89.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('2497teresa','62450','Verenigde Staten','US',85.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('2nd_city_games','BN229QB','Verenigd Koninkrijk','GB',99.9)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('387steven','DE223QS','Verenigd Koninkrijk','GB',99.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('3kidsvon','1567HR','Nederland','NL',72.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('4bb1bd','','België','BE',79.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('6585jonathan','6791','België','BE',78.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('77itanem','27030','Verenigde Staten','US',87.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('954heike','58256','Duitsland','DE',83.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('a1-toys','','Verenigd Koninkrijk','GB',99.7)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('abeku2010','95100','Duitsland','DE',97.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('abigbuy','','Verenigde Staten','US',99.2)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('ab-loz','NG58QU','Verenigd Koninkrijk','GB',99.9)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('aboyzee','','Verenigd Koninkrijk','GB',99.6)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('action_figure_mania','66100','Italië','IT',99.6)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('addtronic','45527','Duitsland','DE',99.4)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('ady2mo','PL99DB','Verenigd Koninkrijk','GB',78.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('aftermath_miniatures','LA46BB','Verenigd Koninkrijk','GB',66.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('ageslight','322000','China','CN',99.8)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('aitenetxe','73277','Duitsland','DE',89.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('aixplay','52222','Duitsland','DE',85.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('akber12312','B202DP','Verenigd Koninkrijk','GB',99.5)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('alanbyx','6220','België','BE',98.8)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('alexb603-v1','SP103AE','Verenigd Koninkrijk','GB',99.7)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('alisasgeschenkewelt2010','60431','Duitsland','DE',95.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('all4yourparty','12557','Duitsland','DE',99.5)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('allemesser','89440','Duitsland','DE',66.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('allforlaptop','','China','CN',99.7)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('alltagshilfen50plus','32130','Duitsland','DE',99.8)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('amaandistribution','B83QW','Verenigd Koninkrijk','GB',99.7)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('amaz0ne','2400','België','BE',59.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('ameisenkeks','','Duitsland','DE',99.1)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('americo1970','3221','Hellevoetsluis,Nederland','NL',82.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('anarndt','50321','Duitsland','DE',91.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('ange01red','CH461PF','Verenigd Koninkrijk','GB',88.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('angeltots6767','DG34DE','Verenigd Koninkrijk','GB',74.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('anita.geyer','2500','België','BE',87.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('annastore','86465','Duitsland','DE',99.7)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('annetrent-us','98155','Verenigde Staten','US',61.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('antares2007','87719','Duitsland','DE',73.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('antikspielzeug','55127','Duitsland','DE',99.9)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('antik-tirol','6330','Oostenrijk','AT',66.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('aquilagames','DY122RH','Verenigd Koninkrijk','GB',93.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('artedhio','81243','Duitsland','DE',99.9)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('art-sinfonie','','Duitsland','DE',68.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('artslim','E50RR','Verenigd Koninkrijk','GB',99.5)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('asimov66','','China','CN',99.2)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('atelier-kathy','4371','Koudekerke,Nederland','NL',62.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('at-modellautos','','Duitsland','DE',74.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('audiator','94375','Duitsland','DE',99.8)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('autoemfasi','53100','Italië','IT',99.3)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('averdo-online','','Duitsland','DE',99.7)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('a-z.111','','Duitsland','DE',58.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('azerty007007','1090','België','BE',97.7)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('babs2208','ME38GS','Verenigd Koninkrijk','GB',67.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('babyfabienne','6372MS','Nederland','NL',75.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('bachpfeiffen','','Duitsland','DE',99.6)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('baeren-und-puppenklinik','70806','Duitsland','DE',67.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('balkan2013','6200','België','BE',62.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('bambinobebe','','Hongkong','HK',90.6)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('bankcroft-de','91522','Duitsland','DE',99.8)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('barbiegirl1232011','LE127FH','Verenigd Koninkrijk','GB',99.7)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('bargain_hut_uk','B976QX','Verenigd Koninkrijk','GB',99.4)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('basman2959','07036','Verenigde Staten','US',100.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('baumarkthandel-versandfrei','96215','Duitsland','DE',99.7)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('baustein15','12163','Duitsland','DE',90.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('beautyzz2009','','Verenigd Koninkrijk','GB',98.9)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('beebouncy67','GL74EX','Verenigd Koninkrijk','GB',99.7)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('belgian-coast','8560','België','BE',83.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('ben1021','43130','Verenigde Staten','US',99.4)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('benvita','60433','Duitsland','DE',69.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('berkshire99','','Verenigd Koninkrijk','GB',99.3)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('berlinerfotoladen*de','','Duitsland','DE',99.8)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('berlin-gamez','12279','Duitsland','DE',99.9)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('bert*s','90562','Duitsland','DE',71.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('best_toys_for_you','65201','Duitsland','DE',94.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('betiwo-shop','86529','Duitsland','DE',56.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('bieke0001','9800','België','BE',74.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('biestl','18276','Duitsland','DE',99.5)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('bigredwarehouse-uk','','Verenigd Koninkrijk','GB',99.3)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('big-spender','94401','Verenigde Staten','US',63.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('bikersstore','4204','Gorinchem,Nederland','NL',60.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('bilderweltencomicladen2009','45468','Duitsland','DE',82.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('billigmann0','15827','Duitsland','DE',99.8)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('bill-markt','20539','Duitsland','DE',99.6)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('bingo-center-deutschland','59269','Duitsland','DE',71.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('bingolink75','96052','Duitsland','DE',99.5)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('black-knight-studios','SL71DP','Verenigd Koninkrijk','GB',98.9)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('bluefrogtoysltd','MK35NQ','Verenigd Koninkrijk','GB',99.9)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('blues4u','','Verenigd Koninkrijk','GB',100.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('boe262','01157','Duitsland','DE',99.7)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('boehmi127','23568','Duitsland','DE',90.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('bookooguru','75160','Verenigde Staten','US',97.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('bookwormbookshop','','Verenigd Koninkrijk','GB',99.8)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('bpzgap','90019','Verenigde Staten','US',99.5)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('brapsmagic','','Verenigde Staten','US',99.9)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('brickcave','7500','België','BE',98.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('brick-store','','Duitsland','DE',86.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('brocanteonline2013','4830','België','BE',78.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('buccaneerbarque','','Verenigde Staten','US',99.2)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('budetrophies','EX238TF','Verenigd Koninkrijk','GB',99.8)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('bunky*','RG263RY','Verenigd Koninkrijk','GB',70.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('buntesteinekeller','50169','Duitsland','DE',99.9)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('bureau-de-change','41569','Duitsland','DE',89.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('buy_send','','Verenigd Koninkrijk','GB',99.4)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('buynowwhynot','','China','CN',99.4)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('buynsave814','B130BL','Verenigd Koninkrijk','GB',99.1)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('buyzaar.eu','','Hongkong','HK',98.9)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('buzz_de','65388','Duitsland','DE',78.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('cantusplanusjackie','YO243BX','Verenigd Koninkrijk','GB',66.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('captainpaulchen','45145','Duitsland','DE',99.9)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('carrostyle11','73046','Italië','IT',69.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('carry1427','2100','België','BE',63.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('carsten4870','24768','Duitsland','DE',99.8)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('cascadejugglingkit','TD57BX','Verenigd Koninkrijk','GB',99.9)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('cedrictheo','4460','België','BE',81.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('celebrityfinearts','','Verenigd Koninkrijk','GB',99.8)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('chaoscards-online','','Verenigd Koninkrijk','GB',99.8)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('charel_de','44532','Duitsland','DE',99.8)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('charlychaps','1020','België','BE',97.4)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('cheadr','60076','Verenigde Staten','US',59.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('cheapbids4u','','Verenigde Staten','US',98.5)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('chessacademy','40627','Duitsland','DE',95.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('chessebook','01219','Duitsland','DE',99.9)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('chinamaizhelun3','','China','CN',99.4)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('chrileca','4933','Oostenrijk','AT',99.8)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('cilla27031979','28010','Italië','IT',99.9)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('ciracosa','SR68AW','Verenigd Koninkrijk','GB',99.9)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('cityandfalconsfan','NE391EL','Verenigd Koninkrijk','GB',92.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('clarelouise09','','Verenigd Koninkrijk','GB',71.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('clearbrookshop2014','','China','CN',65.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('cleverekids-shop','86167','Duitsland','DE',99.4)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('clubhousegames','95060','Verenigde Staten','US',79.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('cmtbelleville','','Verenigd Koninkrijk','GB',99.9)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('cocoyovanny888','01259','Duitsland','DE',99.9)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('collectibles-hamburgde','22085','Duitsland','DE',60.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('collectorsbuddycom','ME168TE','Verenigd Koninkrijk','GB',76.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('comiccomboleipzig','04107','Duitsland','DE',99.9)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('commerce-21','72762','Duitsland','DE',64.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('connexxion_24','33602','Duitsland','DE',99.9)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('conrad-antiquario','13509','Duitsland','DE',90.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('coolcaps4u','54963','Verenigde Staten','US',63.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('corpseguy','','Verenigd Koninkrijk','GB',98.8)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('corubam','53902','Duitsland','DE',79.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('cosmoanddibs','ME45LJ','Verenigd Koninkrijk','GB',99.7)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('cougarrinard','PO20PJ','Verenigd Koninkrijk','GB',99.7)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('creativ_company','','Denemarken','DK',99.1)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('cricket386','42635','Verenigde Staten','US',57.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('crown2788','7140','België','BE',91.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('cthulhu180571','22527','Duitsland','DE',61.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('curioscave','LS287HT','Verenigd Koninkrijk','GB',71.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('curteysminiatures','DN149JN','Verenigd Koninkrijk','GB',63.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('cygnus44','84503','Duitsland','DE',99.9)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('daanbanaan','2950','België','BE',85.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('dag116','48527','Duitsland','DE',99.7)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('daily-deals-ltd','M300HH','Verenigd Koninkrijk','GB',99.7)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('daisybankbooks1','WV148QQ','Verenigd Koninkrijk','GB',82.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('dantefrans','7110','België','BE',66.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('darkstorm28','2771RA','Nederland','NL',98.6)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('darnie01','M230FW','Verenigd Koninkrijk','GB',60.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('darthheg','','Duitsland','DE',66.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('davidstorepuntonet','','Italië','IT',93.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('daydeal2014','MK77DU','Verenigd Koninkrijk','GB',97.9)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('dc-markt','91056','Duitsland','DE',66.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('ddkcarl','2170','België','BE',98.9)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('de_toydealer_de','73035','Duitsland','DE',99.9)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('deal-runner','','Verenigde Staten','US',99.9)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('decopostcards','CO27HT','Verenigd Koninkrijk','GB',99.4)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('dekoart1008','59077','Duitsland','DE',99.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('delforge.jacquesetco','5000','België','BE',69.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('dellamotherduck','8800','België','BE',75.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('deluxe-pro-verkauf','06116','Duitsland','DE',99.6)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('der-baumarkt','49124','Duitsland','DE',99.9)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('dewitte1383','4520','België','BE',92.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('dgilson','83440','Verenigde Staten','US',67.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('diaboloshop','76646','Duitsland','DE',78.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('diannangus2005','CB61BL','Verenigd Koninkrijk','GB',60.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('didier5996','5332','België','BE',78.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('didierng_be','6540','België','BE',58.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('die.gelegenheit','22547','Duitsland','DE',99.9)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('dieeulespielwaren2011','60439','Duitsland','DE',99.7)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('diefarbkleckse','33175','Duitsland','DE',99.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('difirma','38176','Duitsland','DE',81.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('dinies-onlineshop','','Duitsland','DE',91.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('dioplay2012','59519','Duitsland','DE',92.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('discounthomegardenstore','SS129JF','Verenigd Koninkrijk','GB',98.8)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('disney_crazy_forever','48312','Verenigde Staten','US',77.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('dj-mdy','4960','België','BE',99.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('doc_mcshamus','CB80DS','Verenigd Koninkrijk','GB',83.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('doktorfisch111','96472','Duitsland','DE',69.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('dommi1979','60529','Duitsland','DE',66.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('doortje07','5591BE','Nederland','NL',62.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('dorobibi','6560','België','BE',70.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('dr.brucknergmbh','12587','Duitsland','DE',95.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('drachenladen-com','50672','Duitsland','DE',63.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('driley10uk','SO505NT','Verenigd Koninkrijk','GB',87.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('drk102','82418','Duitsland','DE',69.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('dtuttounpo2010','35021','Italië','IT',75.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('dvdamp','SY197DH','Verenigd Koninkrijk','GB',97.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('dyson690','E79BZ','Verenigd Koninkrijk','GB',84.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('eagshop','99867','Duitsland','DE',72.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('ebadgeriow2013','PO376EE','Verenigd Koninkrijk','GB',99.6)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('ee-wee','2713GG','Nederland','NL',73.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('ehlana1404','LN76SA','Verenigd Koninkrijk','GB',99.6)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('eightieschick72','LE159QZ','Verenigd Koninkrijk','GB',99.9)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('elastruhe','82380','Duitsland','DE',75.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('eleanorcollects','','Verenigd Koninkrijk','GB',99.4)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('electricien17','4100','België','BE',64.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('elektrobrueggemann','23919','Duitsland','DE',99.7)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('ellacollectibles','97367','Verenigde Staten','US',86.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('ello4you','99310','Duitsland','DE',99.9)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('enigmagadgetsandgifts','TR73BZ','Verenigd Koninkrijk','GB',99.7)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('enmisport','39108','Duitsland','DE',99.9)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('ericachen2000','','China','CN',94.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('erydayeryday','75976','Verenigde Staten','US',99.4)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('esellitlondon','','Verenigd Koninkrijk','GB',99.7)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('eshopic','','Verenigde Staten','US',98.8)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('ezwinner1206','92336','Verenigde Staten','US',80.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('fabmor77','21049','Italië','IT',63.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('fancy-free-company','65428','Duitsland','DE',79.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('fantasia-spielzeug.de','14050','Duitsland','DE',99.8)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('fantasygamingworkshop','S207JN','Verenigd Koninkrijk','GB',99.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('faro_2002','45279','Duitsland','DE',79.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('federationdesigns','CT46AQ','Verenigd Koninkrijk','GB',99.8)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('ferreira-de-oliveira','34127','Duitsland','DE',77.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('figuren-und-mehr','52379','Duitsland','DE',99.7)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('finlaysophie','NR33NR','Verenigd Koninkrijk','GB',99.4)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('firestartoys','WD258AJ','Verenigd Koninkrijk','GB',99.5)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('firetop_mountain','NG163AQ','Verenigd Koninkrijk','GB',99.8)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('fishbabblez','SK138BB','Verenigd Koninkrijk','GB',82.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('fit4form','92648','Duitsland','DE',99.4)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('fittieke','2223','België','BE',93.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('flames_n_games_juggling_store','BN99BF','Verenigd Koninkrijk','GB',99.6)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('flowerpower0803','LS104NF','Verenigd Koninkrijk','GB',98.6)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('fonorama','3520','België','BE',82.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('footballjoda','22391','Duitsland','DE',70.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('fpor1970','64100','Italië','IT',99.3)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('frankaustralien','45472','Duitsland','DE',74.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('fraoster','51061','Duitsland','DE',97.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('freovendo','12623','Duitsland','DE',99.4)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('fridavankemseke','3331KE','Nederland','NL',98.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('fritz123blau','50739','Duitsland','DE',99.8)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('frobis','21680','Duitsland','DE',78.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('fullhousetrading','RG75SF','Verenigd Koninkrijk','GB',99.9)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('fun_learning','BN31AR','Verenigd Koninkrijk','GB',59.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('funandcashcom','TW80EW','Verenigd Koninkrijk','GB',99.5)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('funcellbud','14733','Verenigde Staten','US',99.7)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('funkyleisure','','Verenigd Koninkrijk','GB',99.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('gadgetmagicstore','NG123GZ','Verenigd Koninkrijk','GB',99.1)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('gadgetspace','OL165LB','Verenigd Koninkrijk','GB',99.4)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('gameland-groningen','','Nederland','NL',81.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('gamenerdz','75074','Verenigde Staten','US',99.6)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('gamesquest','','Verenigd Koninkrijk','GB',99.2)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('gd-world','49577','Duitsland','DE',99.9)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('geggs2003','','Verenigd Koninkrijk','GB',99.8)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('general-trust','3312CM','Nederland','NL',95.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('geniehobbies','49705','Verenigde Staten','US',61.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('gerrutcamaro','1567','Assendelft,Nederland','NL',80.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('getgreasy','56076','Duitsland','DE',76.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('giallo_42','22077','Italië','IT',99.9)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('gigagadgets_be','2845','België','BE',96.6)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('gijon55','95680','Verenigde Staten','US',85.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('gingernpickles','85310','Verenigde Staten','US',86.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('giocondo-faber','52045','Italië','IT',99.2)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('gitarren-spiel','21680','Duitsland','DE',67.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('glamour-kids24','31683','Duitsland','DE',57.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('glenrue','LE101LF','Verenigd Koninkrijk','GB',69.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('glitterbabe1929','NG41FB','Verenigd Koninkrijk','GB',94.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('global_megastore','','Verenigd Koninkrijk','GB',99.3)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('global450','','Duitsland','DE',97.9)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('glunderw0rld','','Nederland','NL',96.7)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('god4memin','','Verenigde Staten','US',99.8)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('gohastings','','Verenigde Staten','US',99.3)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('golden_arrow_archery','BR33JL','Verenigd Koninkrijk','GB',76.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('goldtimer','','Verenigde Staten','US',99.9)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('golfvs','78141','Duitsland','DE',94.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('good_toys','59399','Duitsland','DE',99.6)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('goodies-for-oldtoys','','Duitsland','DE',99.5)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('gp_military_4eva','FY15DY','Verenigd Koninkrijk','GB',64.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('greenangelx','NN168EL','Verenigd Koninkrijk','GB',86.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('greensofgloucestershireonline','GL181HJ','Verenigd Koninkrijk','GB',99.9)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('gregg342000','37040','Verenigde Staten','US',99.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('gr-tech-it','ME142EA','Verenigd Koninkrijk','GB',99.5)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('gtspeedltdc2u','DL170PB','Verenigd Koninkrijk','GB',65.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('gun711','2470','België','BE',98.3)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('habtari','14089','Duitsland','DE',99.6)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('hackspett1951','2800','België','BE',89.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('haest_de','38239','Duitsland','DE',74.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('hairsism','322000','China','CN',99.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('hajogeur','4824JJ','Nederland','NL',99.7)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('hanaweb','01069','Duitsland','DE',99.8)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('hannelore9716','56410','Duitsland','DE',99.7)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('happybear*2010','91056','Duitsland','DE',99.9)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('hareos','64295','Duitsland','DE',57.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('haseundigel2014','21614','Duitsland','DE',95.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('hawaille','4920','België','BE',90.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('heikeundich','06749','Duitsland','DE',99.6)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('hgm2003','60625','Verenigde Staten','US',100.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('hobbyruimte','8300','België','BE',64.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('hochmobile1','97877','Duitsland','DE',99.4)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('hoffnungs-volle','76646','Duitsland','DE',99.2)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('hoher-brunnen','92345','Duitsland','DE',78.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('hoisin-derek','63067','Duitsland','DE',100.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('home-gallery','','Verenigde Staten','US',99.2)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('homeoffice2014','','Verenigd Koninkrijk','GB',99.8)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('honeychileryder','80796','Duitsland','DE',96.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('hoombletoys','PO92FR','Verenigd Koninkrijk','GB',99.9)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('horakl-de','41239','Duitsland','DE',99.8)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('hornschu2011','32257','Duitsland','DE',99.8)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('howlback','8094AN','Nederland','NL',0.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('hph1956','53560','Duitsland','DE',99.6)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('ht-uk','E50NS','Verenigd Koninkrijk','GB',99.2)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('hugos-hut','PL126WQ','Verenigd Koninkrijk','GB',99.5)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('hursts-garage74','77767','Duitsland','DE',98.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('iamastar09','6800','Oostenrijk','AT',99.2)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('ibanez06','30033','Italië','IT',63.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('ibeiregali','37124','Italië','IT',82.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('ideeundspiel.grosse','14806','Duitsland','DE',99.3)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('iffbiff','27703','Verenigde Staten','US',73.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('iks-uk','','Verenigd Koninkrijk','GB',99.8)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('ikz_distribution','','Verenigd Koninkrijk','GB',92.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('import_international','1000','België','BE',60.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('infinity_games','CF245HJ','Verenigd Koninkrijk','GB',99.2)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('info-on-collectibles','8560','België','BE',99.8)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('internetdealsdirectno1','BT790TA','Verenigd Koninkrijk','GB',70.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('internetgiftstore2012','','Verenigd Koninkrijk','GB',99.5)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('itsonlyarabbit','PE217HL','Verenigd Koninkrijk','GB',76.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('itzagift','S426UL','Verenigd Koninkrijk','GB',99.9)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('jacques2212','6060','België','BE',97.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('jadestone64','6980','België','BE',89.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('jan1212b','LE93GN','Verenigd Koninkrijk','GB',97.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('janepeogeot206','WS66PE','Verenigd Koninkrijk','GB',81.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('japanworld-shop','00152','Italië','IT',99.6)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('jessica82jessica','5472PM','Nederland','NL',56.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('jieffe_be','7502','België','BE',78.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('jochen-heil-toys','','Duitsland','DE',99.9)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('john41johann','EX41NE','Verenigd Koninkrijk','GB',57.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('johns-modelcarsandtrains','','Nederland','NL',99.9)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('jojoyoyo_7','9600','België','BE',78.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('jokito','74535','Duitsland','DE',99.6)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('jolanda2005a','7607','Almelo,Nederland','NL',85.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('jondo1','SR84BQ','Verenigd Koninkrijk','GB',99.7)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('joskeq','6467HA','Nederland','NL',68.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('jr-spielwaren','21465','Duitsland','DE',99.9)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('jugglegames99','LE101UB','Verenigd Koninkrijk','GB',90.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('k_en_d_used_items','6446BX','Nederland','NL',60.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('kabaviolator','95030','Duitsland','DE',69.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('kamithewookie','76571','Duitsland','DE',82.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('kamtecmodels','','Verenigd Koninkrijk','GB',99.9)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('kapitell4','06526','Duitsland','DE',99.9)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('kasing0','96465','Duitsland','DE',99.8)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('kaufhaus-fleischer','27711','Duitsland','DE',71.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('kds-tuning','44789','Duitsland','DE',99.5)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('ketivofbe','','België','BE',76.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('ketoune1943','2140','België','BE',81.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('key_mel','DL146AE','Verenigd Koninkrijk','GB',91.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('kiarenzafunnydreams','65124','Italië','IT',99.9)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('kiddy-bikes_at','3484','Oostenrijk','AT',96.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('kids.toys.london','','Verenigd Koninkrijk','GB',99.6)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('kidsbestshop','51069','Duitsland','DE',99.9)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('kidsplanet24','','Verenigd Koninkrijk','GB',99.8)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('kidssportandfun','91056','Duitsland','DE',99.9)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('kiertjeinwonderland','3037EM','Nederland','NL',64.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('kieselsteinchen60','29643','Duitsland','DE',67.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('kimmy11mark','','Verenigd Koninkrijk','GB',85.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('kistenparty','','Duitsland','DE',99.5)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('klatschmohn212','83451','Duitsland','DE',65.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('klicky-paradies','67271','Duitsland','DE',99.4)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('klicky-town','44623','Duitsland','DE',99.9)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('knut3812','55304','Verenigde Staten','US',63.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('kogitho','58553','Duitsland','DE',99.7)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('kokojo-de','49838','Duitsland','DE',99.5)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('kontor68','50858','Duitsland','DE',64.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('kooky_kids','','Verenigd Koninkrijk','GB',99.6)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('koshtra','PE339AE','Verenigd Koninkrijk','GB',99.9)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('kremers-schatzkiste','63456','Duitsland','DE',99.9)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('krilli8','8181','Oostenrijk','AT',93.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('kullertrulla-spielwarenhandel','','Duitsland','DE',93.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('kunterbuntlaedele2','76571','Duitsland','DE',99.7)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('kurtvdp','8510','België','BE',58.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('ladreas','','Duitsland','DE',99.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('lannanaris','E14RH','Verenigd Koninkrijk','GB',72.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('lapichon','','België','BE',81.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('lareno09','95666','Duitsland','DE',99.9)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('latecanadian','98026','Verenigde Staten','US',89.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('latitudine42comics','04011','Italië','IT',76.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('lavignarella2009','00049','Italië','IT',99.4)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('leatherandstuff-shop','','Verenigd Koninkrijk','GB',99.9)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('lederjeans-de','88499','Duitsland','DE',99.9)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('lenusjasshop','65232','Duitsland','DE',56.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('librejoggen','90596','Duitsland','DE',99.8)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('lisaanne1mkk','53954','Verenigde Staten','US',99.6)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('litti1977','22417','Duitsland','DE',79.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('littlebill2450','60175','Verenigde Staten','US',56.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('logotuerlich','58566','Duitsland','DE',71.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('lotoons3','','Verenigde Staten','US',99.1)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('loveoldtoys','86368','Duitsland','DE',87.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('lpavia2012','33446','Verenigde Staten','US',70.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('lucino123','74535','Duitsland','DE',99.9)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('lumberguy17383','07819','Duitsland','DE',57.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('luna65edera','09045','Italië','IT',95.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('luxegoods4sale','WD245DZ','Verenigd Koninkrijk','GB',95.2)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('m*4*r','5640','België','BE',98.5)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('m_lmodels','WF81JN','Verenigd Koninkrijk','GB',60.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('m-79-heidi','','Duitsland','DE',99.6)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('macimweb','96450','Duitsland','DE',84.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('macyeck','26452','Duitsland','DE',96.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('maddix2009','CO102SA','Verenigd Koninkrijk','GB',99.9)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('madknotter','SG20QD','Verenigd Koninkrijk','GB',91.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('maggie73063','02904','Verenigde Staten','US',97.8)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('magichandel99','48268','Duitsland','DE',99.5)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('magicnevin','','Verenigd Koninkrijk','GB',99.8)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('magpiesvintageshop','ST103JE','Verenigd Koninkrijk','GB',57.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('majunik','42857','Duitsland','DE',79.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('maldon-jewellery','','Verenigd Koninkrijk','GB',73.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('mandmfurnitureuk','SG87AG','Verenigd Koninkrijk','GB',88.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('manny91948','32602','Duitsland','DE',99.6)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('mansion212','','Verenigd Koninkrijk','GB',99.7)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('manu75emanuele','10145','Italië','IT',90.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('mara-jane2008','','Duitsland','DE',97.5)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('mariposa-shop','13507','Duitsland','DE',99.4)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('markenwarenshop_2012','71540','Duitsland','DE',99.9)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('markoramaworld','07416','Verenigde Staten','US',80.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('marktkramroyal','61138','Duitsland','DE',71.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('martinlc81','OX43AY','Verenigd Koninkrijk','GB',99.7)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('maruzzell2','84043','Italië','IT',99.9)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('marvinthemartian_de','12355','Duitsland','DE',100.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('mato519','G128DY','Verenigd Koninkrijk','GB',95.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('mattyallen12010','LS104EN','Verenigd Koninkrijk','GB',97.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('max-discounts','NE209JT','Verenigd Koninkrijk','GB',99.4)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('maxika','44263','Duitsland','DE',89.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('maxxtools','','België','BE',97.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('mayaron','','Verenigde Staten','US',99.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('mbbay12345','','Verenigde Staten','US',98.7)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('medikussi','','Duitsland','DE',99.7)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('mega-bikes','41470','Duitsland','DE',99.6)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('mein_neuesundaltes','04435','Duitsland','DE',99.2)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('meiradario','8754LD','Nederland','NL',99.9)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('melgil57','PE47PT','Verenigd Koninkrijk','GB',76.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('meshdiamond','65203','Duitsland','DE',99.1)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('mfggethles','98553','Duitsland','DE',99.9)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('micheanne','1800','België','BE',56.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('miesenmas.vintage.toys.kitchenware','2512','''s-Gravenhage,Nederland','NL',78.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('mikeplatell','CB61LE','Verenigd Koninkrijk','GB',57.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('mikipin','58135','Duitsland','DE',77.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('mikogiocattolistore','00036','Italië','IT',99.7)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('miniature_empire_online_shop','RM14DG','Verenigd Koninkrijk','GB',99.9)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('minisryou','TF43UP','Verenigd Koninkrijk','GB',95.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('miraculix_bunte_spielewelt','44329','Duitsland','DE',99.8)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('mistercolleco','53498','Duitsland','DE',99.9)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('mmurray6670','KY128XH','Verenigd Koninkrijk','GB',99.8)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('modellbahn-rinteln','33607','Duitsland','DE',99.8)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('models4hobby09','DL170PB','Verenigd Koninkrijk','GB',76.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('moggy1990trading','NN155AU','Verenigd Koninkrijk','GB',99.8)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('mokeyr','','Verenigd Koninkrijk','GB',99.8)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('mondostardust','20091','Italië','IT',69.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('monique5832','5251PC','Nederland','NL',98.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('mooiweertje22','6882HM','Nederland','NL',82.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('mookin66','B692HA','Verenigd Koninkrijk','GB',58.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('moominfluffy','','Verenigd Koninkrijk','GB',99.9)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('moonflower1958','38536','Duitsland','DE',60.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('morbidmasks','CT103JJ','Verenigd Koninkrijk','GB',99.6)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('more4urmoney09','M125QH','Verenigd Koninkrijk','GB',99.4)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('morlesfritz','','Duitsland','DE',99.6)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('morpheusdesire','83709','Verenigde Staten','US',87.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('motelslover','4890','België','BE',88.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('mr_juggles','BN24QN','Verenigd Koninkrijk','GB',86.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('mrmouse999','','Verenigd Koninkrijk','GB',99.8)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('mruwlon','','Duitsland','DE',93.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('ms_toys','95689','Duitsland','DE',82.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('msspielwaren','24649','Duitsland','DE',84.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('mssportsandtoys','58239','Duitsland','DE',99.5)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('msv1939','','Duitsland','DE',61.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('muenzenede0868','94121','Duitsland','DE',87.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('multihouse','','Nederland','NL',99.1)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('muppetpasterian','TF28QL','Verenigd Koninkrijk','GB',61.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('musikhaus-kirstein','86956','Duitsland','DE',99.8)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('muskelkatersport','','Duitsland','DE',94.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('mwbuerobedarf','13509','Duitsland','DE',94.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('mydearbarbie','','Hongkong','HK',99.2)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('mymemory-uk','JE45WH','Verenigd Koninkrijk','GB',99.6)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('myshop-direkt','73479','Duitsland','DE',69.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('mystykal_man','48170','Verenigde Staten','US',99.9)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('nachrichtvonsam','','Duitsland','DE',99.2)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('nanainch','80796','Duitsland','DE',83.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('nane9911','6200','België','BE',89.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('narla2407','IP28GR','Verenigd Koninkrijk','GB',99.9)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('neffy_shop','25087','Italië','IT',98.4)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('neodym-24','75172','Duitsland','DE',99.9)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('netta5454','41238','Duitsland','DE',99.2)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('new-old-store','95511','Duitsland','DE',99.5)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('newpolarity','48634','Verenigde Staten','US',81.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('nick_ayres','LE194PH','Verenigd Koninkrijk','GB',98.4)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('nokanspok','S59FB','Verenigd Koninkrijk','GB',99.8)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('nokia35','1020','België','BE',96.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('nostalgie-shop','','Duitsland','DE',99.6)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('no-toys','82487','Duitsland','DE',98.6)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('nourra','','België','BE',94.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('nox1982','1300','België','BE',91.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('nsx1nsx_nl','','Nederland','NL',92.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('occapub','5080','België','BE',98.8)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('oddsngods','WA110DL','Verenigd Koninkrijk','GB',64.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('oh-bxl','1160','België','BE',71.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('oktopussi','82538','Duitsland','DE',67.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('ollienamber','YO422DF','Verenigd Koninkrijk','GB',79.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('olliprint','53842','Duitsland','DE',99.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('olli-toys','76571','Duitsland','DE',57.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('onlineshop-paradies','22305','Duitsland','DE',99.9)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('onlineversandhaus','12555','Duitsland','DE',99.6)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('opawi51','9220','België','BE',94.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('origineelgeschenkje','9320','België','BE',61.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('otherlandgifts','N183BH','Verenigd Koninkrijk','GB',99.8)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('ourpamperedhome','86403','Verenigde Staten','US',99.2)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('outdoorartikel24','73434','Duitsland','DE',99.8)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('outlawsonline2005','AL36HP','Verenigd Koninkrijk','GB',96.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('overwatchcommand','S425JJ','Verenigd Koninkrijk','GB',59.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('packorder','BT251LE','Verenigd Koninkrijk','GB',99.9)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('packripper','78411','Verenigde Staten','US',99.8)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('paj89','ZE29BG','Verenigd Koninkrijk','GB',73.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('palettenware24','96215','Duitsland','DE',99.6)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('palmisso','67659','Duitsland','DE',99.7)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('pamann705','CH442DN','Verenigd Koninkrijk','GB',99.8)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('pamelaallsortsofeverything','SO529HR','Verenigd Koninkrijk','GB',81.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('pantherknight333','CO168FQ','Verenigd Koninkrijk','GB',99.8)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('paperglenn','54241','Verenigde Staten','US',98.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('pappbecher','59077','Duitsland','DE',99.7)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('pappeter','21481','Duitsland','DE',98.4)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('parmaluca','43100','Italië','IT',84.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('patb_it','','Italië','IT',99.9)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('patito7','90028','Verenigde Staten','US',57.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('paul4557','91074','Duitsland','DE',78.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('pcarena-bristol','','Verenigd Koninkrijk','GB',99.6)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('pdk-ltd','EX28QW','Verenigd Koninkrijk','GB',99.8)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('perlenonline','','China','CN',99.1)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('personal_kids','1562ZG','Nederland','NL',0.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('peterpanlibreria','20052','Italië','IT',99.8)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('pikes*peak','29597','Duitsland','DE',85.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('piruparu','40100','Italië','IT',99.8)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('plaguegames','KA260QD','Verenigd Koninkrijk','GB',98.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('planetextra','74374','Duitsland','DE',99.9)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('plasteelaste_de','04509','Duitsland','DE',61.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('play-dendros24','','Duitsland','DE',99.5)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('playfritz1','53119','Duitsland','DE',99.9)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('playmoking','47638','Duitsland','DE',99.8)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('playmo-land','46325','Duitsland','DE',99.8)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('playmo-of-fame','79111','Duitsland','DE',74.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('playmo-pirat','44803','Duitsland','DE',99.9)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('playtowncologne','53842','Duitsland','DE',99.9)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('plominator','47259','Duitsland','DE',95.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('pp-prima-preise','97688','Duitsland','DE',99.9)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('pred78','1713JL','Nederland','NL',87.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('preisraketen','','Duitsland','DE',99.9)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('preistreiber2004','97320','Duitsland','DE',100.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('present-house','49751','Duitsland','DE',84.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('primeshop','','Duitsland','DE',96.5)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('professional39','95127','Italië','IT',99.5)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('profishop3000','80999','Duitsland','DE',99.6)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('publicenemy2006','5801SG','Nederland','NL',60.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('puth76','6155','Puth,Nederland','NL',79.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('pvenl_dtcuih','3068LG','Nederland','NL',0.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('pwood13660','SM13LA','Verenigd Koninkrijk','GB',99.3)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('quanquaneshop','KT33QF','Verenigd Koninkrijk','GB',99.4)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('quickdraw_toys_and_party','','Verenigd Koninkrijk','GB',99.5)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('raflees132','EX81AD','Verenigd Koninkrijk','GB',89.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('rantanplouf','5000','België','BE',74.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('rattedlego','MK187EG','Verenigd Koninkrijk','GB',99.8)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('ratzekatz112','10437','Duitsland','DE',84.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('ravenslair2010','DE222FP','Verenigd Koninkrijk','GB',87.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('rc-vetti','72488','Duitsland','DE',99.6)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('rebel_planet','22307','Duitsland','DE',99.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('rectus72','PL144NQ','Verenigd Koninkrijk','GB',100.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('regi.na','87662','Duitsland','DE',85.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('reinke.shop','58739','Duitsland','DE',62.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('relaxdays','06112','Duitsland','DE',99.6)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('remy1212','4834NG','Nederland','NL',83.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('richminust','BB112QX','Verenigd Koninkrijk','GB',75.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('rikkihunter','7100','België','BE',96.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('riyashop','50170','Duitsland','DE',99.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('rocksteddy4life','55008','Verenigde Staten','US',70.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('ronald2511','5236WT','Nederland','NL',89.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('rossimario80','80054','Italië','IT',96.7)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('rote_irma','96472','Duitsland','DE',78.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('rotzname','50765','Duitsland','DE',96.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('ruck-zuck-da-team','50670','Duitsland','DE',99.9)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('rusin138','24012','Verenigde Staten','US',99.9)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('rutabaga5','52756','Verenigde Staten','US',98.4)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('ryehill_retail','CA25PT','Verenigd Koninkrijk','GB',99.4)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('rz-shop','49635','Duitsland','DE',99.7)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('safari-island','','Verenigd Koninkrijk','GB',99.6)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('sallys_rocking_horses_2004','SY156BH','Verenigd Koninkrijk','GB',93.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('sammelparadise','','Duitsland','DE',99.7)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('sammlerkontorshop','61273','Duitsland','DE',66.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('sammlershop-dresden','01067','Duitsland','DE',99.6)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('sammlertoys','90610','Duitsland','DE',69.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('sandys-laedle','','Duitsland','DE',99.7)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('sansui19','5321VB','Nederland','NL',86.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('sasso6_it','22069','Italië','IT',84.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('satiropa','2300','België','BE',93.1)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('sbohs','','Duitsland','DE',67.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('schlauchverkauf','90427','Duitsland','DE',99.9)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('schluchti1860','85452','Duitsland','DE',70.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('schmet1','5100','België','BE',85.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('schneewittchen-ohne-zwerge','22956','Duitsland','DE',78.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('schoenespiele2012','67316','Duitsland','DE',95.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('scott1982-2008','WD79DY','Verenigd Koninkrijk','GB',67.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('sdi_danys_87','72024','Italië','IT',99.8)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('seb_belle','4100','België','BE',99.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('seb0835','CB12TP','Verenigd Koninkrijk','GB',99.7)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('sedent_de','42781','Duitsland','DE',99.1)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('seilschaft-design','25524','Duitsland','DE',99.9)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('sell-il','','Verenigde Staten','US',98.9)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('sell-tex','32609','Duitsland','DE',99.5)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('sennerin24','75179','Duitsland','DE',61.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('serjoga-cd','47167','Duitsland','DE',99.7)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('setro84','','Duitsland','DE',98.8)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('s-handelsagentur','21335','Duitsland','DE',81.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('shop_smart10','B64DY','Verenigd Koninkrijk','GB',99.2)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('shyne_products','TW50AJ','Verenigd Koninkrijk','GB',99.5)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('sickyanni','WF93DQ','Verenigd Koninkrijk','GB',72.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('siddutchman','3075LG','Nederland','NL',73.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('silver-sue','TQ27QG','Verenigd Koninkrijk','GB',99.8)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('simasiamkatze','85053','Duitsland','DE',99.7)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('simbabodo2012','6001','België','BE',59.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('sim-saja-bim','32278','Duitsland','DE',100.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('sj5554','DN47JD','Verenigd Koninkrijk','GB',85.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('skai-asiatika','55606','Duitsland','DE',99.9)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('skeet0673','','Bulgarije','BG',79.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('skoot6612','2586GD','Nederland','NL',69.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('sky_high_kites','HP202SQ','Verenigd Koninkrijk','GB',99.7)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('skywalk154','47918','Duitsland','DE',92.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('small_terrain','BA149PG','Verenigd Koninkrijk','GB',66.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('softensive','33104','Duitsland','DE',99.9)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('softtoyscollectionuk','HP219DE','Verenigd Koninkrijk','GB',82.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('soft-vinyl-club','29221','Duitsland','DE',77.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('sopowarenhandel','49477','Duitsland','DE',99.7)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('spal9420','','Verenigd Koninkrijk','GB',79.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('spartacus197112','1090','Oostenrijk','AT',99.6)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('spass_am_shoppen_321','58339','Duitsland','DE',99.9)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('spassmaxe','89426','Duitsland','DE',86.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('spassprofi','06258','Duitsland','DE',99.7)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('specialproductsholland','','Nederland','NL',66.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('speedman19','42799','Duitsland','DE',81.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('spielbox','50765','Duitsland','DE',99.2)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('spiele_vlothoer','32602','Duitsland','DE',74.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('spielefuer1001nacht','12163','Duitsland','DE',95.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('spielfreunde','','Duitsland','DE',99.3)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('spielkrabbe','86316','Duitsland','DE',56.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('spieltraumspiel','93462','Duitsland','DE',56.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('spielwaren-barth','66564','Duitsland','DE',99.9)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('spielwaren-jakob-ug','34323','Duitsland','DE',99.9)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('spielzeugalarm_aachen','52076','Duitsland','DE',99.7)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('spielzeug-kabinett','20259','Duitsland','DE',99.8)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('spielzeugmeier','82205','Duitsland','DE',97.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('spielzeugparadies-tauschladen','12435','Duitsland','DE',85.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('sports_locker1','RM112HX','Verenigd Koninkrijk','GB',99.5)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('sportsdirect_outlet','','Verenigd Koninkrijk','GB',98.7)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('squirrelpoker','SO456AX','Verenigd Koninkrijk','GB',99.7)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('starbase8','','Duitsland','DE',83.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('stealadealltd','','Verenigd Koninkrijk','GB',99.6)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('steinekiste','49076','Duitsland','DE',99.8)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('steppenstampfer','24143','Duitsland','DE',69.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('stewdcat','80237','Verenigde Staten','US',99.4)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('stez9669','DH15PX','Verenigd Koninkrijk','GB',70.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('stockton-stuff','78664','Verenigde Staten','US',99.9)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('stoeberecke-kinderwelt','27755','Duitsland','DE',99.8)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('stormridersports','SY233HQ','Verenigd Koninkrijk','GB',77.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('stormyfort.toyshopco','DA110JN','Verenigd Koninkrijk','GB',99.8)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('stortfordtoys','','Verenigd Koninkrijk','GB',99.7)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('stoss2','97078','Duitsland','DE',99.7)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('straighttoyou','PR25PB','Verenigd Koninkrijk','GB',99.7)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('stuboy300','PL199FQ','Verenigd Koninkrijk','GB',90.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('stubzy54','B744LX','Verenigd Koninkrijk','GB',99.4)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('stummel26','24867','Duitsland','DE',99.8)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('stu-n-fran','TS14LB','Verenigd Koninkrijk','GB',74.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('suescurios1','LN122AF','Verenigd Koninkrijk','GB',99.7)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('sugie30','8310','België','BE',99.8)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('sununiverse','95014','Italië','IT',99.4)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('superduperpublications','29615','Verenigde Staten','US',99.7)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('susanne-wagners-shop','35315','Duitsland','DE',99.7)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('suspend-your-disbelief-inc','50315','Verenigde Staten','US',99.7)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('svegl','SG99SH','Verenigd Koninkrijk','GB',95.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('swiffermaus','73272','Duitsland','DE',99.5)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('swl-1_at','5561','Oostenrijk','AT',99.7)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('tabletopgametime','49315','Verenigde Staten','US',99.9)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('tamir36','65779','Duitsland','DE',99.8)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('tanithtk2271','5060','België','BE',66.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('targetstores','91761','Verenigde Staten','US',98.5)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('taucherxl','95339','Duitsland','DE',99.7)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('tbarte1','86316','Duitsland','DE',66.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('tcconvoyx','','Verenigd Koninkrijk','GB',57.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('teewelt2011','83278','Duitsland','DE',74.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('teilegustav','72127','Duitsland','DE',99.7)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('telstar417','SA146HA','Verenigd Koninkrijk','GB',99.7)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('the-active-life-store','','Verenigd Koninkrijk','GB',99.7)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('thebast_deal','40591','Duitsland','DE',99.9)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('the-bitz-store','HR81AA','Verenigd Koninkrijk','GB',99.2)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('the-gift-and-gadget-store-online','','Verenigd Koninkrijk','GB',99.6)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('thelittlebrickco','BN208JJ','Verenigd Koninkrijk','GB',95.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('thepaperbagstorelimited','CM12QX','Verenigd Koninkrijk','GB',93.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('thereason-1','53489','Duitsland','DE',99.3)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('thermit0475','1082','België','BE',85.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('thesilencer2001','04758','Duitsland','DE',97.8)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('thinkprice','','Verenigd Koninkrijk','GB',99.5)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('thomasvangelooven','3600','België','BE',72.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('tiktaktoo-spielinseln','','Duitsland','DE',99.8)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('timetrove','17931','Verenigde Staten','US',95.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('tinned-fruit','GL528TD','Verenigd Koninkrijk','GB',90.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('t-k-421','NE612HJ','Verenigd Koninkrijk','GB',80.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('tolle-ideen-shop','87487','Duitsland','DE',99.9)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('tolwin','61194','Duitsland','DE',71.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('tomaly483','7090','België','BE',67.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('tommysimpson','','Duitsland','DE',99.9)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('tony1961anton','','Verenigd Koninkrijk','GB',83.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('toolshed22','WS124AG','Verenigd Koninkrijk','GB',56.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('toy.factory','96472','Duitsland','DE',99.8)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('toyland-1','PR21JA','Verenigd Koninkrijk','GB',98.7)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('toys_hunter_ita','00172','Italië','IT',76.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('toysandmanymore2','68775','Duitsland','DE',68.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('toysandmore-riedl','99087','Duitsland','DE',99.9)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('toysathome24','','Duitsland','DE',92.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('toys-brands','64578','Duitsland','DE',99.8)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('toysfiguresandmore','41065','Duitsland','DE',99.9)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('toys-for-fun24','22145','Duitsland','DE',99.9)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('toysoldiers33','3571XT','Nederland','NL',89.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('toysruscanada','L5R3W5','Canada','CA',98.1)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('toysworld_onlineshop','33334','Duitsland','DE',99.7)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('toy-teufel','18146','Duitsland','DE',99.9)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('tpm.kors','1614KJ','Nederland','NL',66.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('traderbear68','97113','Verenigde Staten','US',70.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('treadhead2004','NG72BY','Verenigd Koninkrijk','GB',99.9)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('trendy-teppich','','Duitsland','DE',99.9)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('trevor_weather','PO215TD','Verenigd Koninkrijk','GB',58.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('tritexsports','ST163PX','Verenigd Koninkrijk','GB',99.9)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('troedel_tobi','33378','Duitsland','DE',99.8)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('trulygifted_uk','TR183JH','Verenigd Koninkrijk','GB',99.7)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('tuliptg','SL99EA','Verenigd Koninkrijk','GB',73.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('turbocitro','','Verenigd Koninkrijk','GB',64.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('twieto','81827','Duitsland','DE',99.3)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('twisted-pinnacle-games','S418XW','Verenigd Koninkrijk','GB',76.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('tygkg_889','','Verenigde Staten','US',64.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('ubandu-handel','69259','Duitsland','DE',99.4)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('ukdragontoys','','Verenigd Koninkrijk','GB',70.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('unbeatablesales','08701','Verenigde Staten','US',98.7)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('unbeatablesales-us','08701','Verenigde Staten','US',0.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('undertaker0611','4251BR','Nederland','NL',91.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('universal_miniatures','','Verenigd Koninkrijk','GB',69.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('urbitrend_collect','8450','België','BE',98.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('value-toys','71034','Duitsland','DE',67.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('van1974','NE331RS','Verenigd Koninkrijk','GB',98.9)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('veilchen210','33829','Duitsland','DE',99.4)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('versand-la-vivi','','Duitsland','DE',99.8)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('vicasso','63667','Duitsland','DE',99.7)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('viertheeacht','1745','België','BE',67.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('viking-enterprises','YO105DD','Verenigd Koninkrijk','GB',70.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('vintagexplosion','','Nederland','NL',96.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('vioks-de','28307','Duitsland','DE',99.2)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('visente2015','01522','Verenigde Staten','US',76.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('vliegmachien','3020','België','BE',58.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('voeing*de','','Duitsland','DE',99.8)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('vulkansurfer','','Duitsland','DE',99.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('waldmarathoni','21502','Duitsland','DE',99.9)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('warehouse-clearance-store','BN436NZ','Verenigd Koninkrijk','GB',98.7)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('warenreich','90471','Duitsland','DE',99.7)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('watso_keith','BD159JA','Verenigd Koninkrijk','GB',61.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('wayfair','74401','Verenigde Staten','US',99.4)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('wecostlessstore','NG123GZ','Verenigd Koninkrijk','GB',99.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('wendy2152','MK454AH','Verenigd Koninkrijk','GB',66.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('wholesale-solutions-ltd','','Verenigd Koninkrijk','GB',99.5)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('whybee-de','','Verenigd Koninkrijk','GB',99.6)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('whypaymore','','Verenigde Staten','US',99.7)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('wickey_de','52538','Duitsland','DE',98.9)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('wightstuff2014','PO369LQ','Verenigd Koninkrijk','GB',68.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('willie_wapper','1628RL','Nederland','NL',89.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('willson2346','NN60LS','Verenigd Koninkrijk','GB',99.7)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('willyandjazz','','Nederland','NL',100.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('wilsons_direct2public','G415SW','Verenigd Koninkrijk','GB',99.6)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('wim-shop','74542','Duitsland','DE',99.7)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('windspiele_de','26180','Duitsland','DE',56.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('witteoctopus','8310','België','BE',97.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('wlan7102','17744','Verenigde Staten','US',60.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('wolffstore_gmbh','41334','Duitsland','DE',99.5)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('wonderdeals-be','','België','BE',97.5)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('world-of-bitz','12101','Duitsland','DE',93.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('wotseriekelepelstraat','4664BN','Nederland','NL',56.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('wowtastic_uk','NR136PR','Verenigd Koninkrijk','GB',99.8)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('wtouk','RG264JT','Verenigd Koninkrijk','GB',90.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('wwgbr','12165','Duitsland','DE',79.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('www.gameworld.de','28201','Duitsland','DE',99.9)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('www.managertoys.de','74357','Duitsland','DE',99.5)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('www_fantasy_toystore_de','','Duitsland','DE',99.5)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('www_lopo24_de','68766','Duitsland','DE',99.5)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('www_markenwelt-voegele_de','79108','Duitsland','DE',76.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('www_spielzeug24_de','28844','Duitsland','DE',80.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('www_susis-blubberblasen_de','97422','Duitsland','DE',99.8)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('www-shop4you24h-de','','Duitsland','DE',99.6)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('www-spielgeschenke-de','04862','Duitsland','DE',99.4)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('wyrmwick','GL43JJ','Verenigd Koninkrijk','GB',84.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('xavvv2008','6700','België','BE',91.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('xmaschiine','59174','Duitsland','DE',95.5)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('yair1956','','Verenigde Staten','US',99.3)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('yannick0993','2050','België','BE',87.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('yeoldecostumeshoppe','LL143YE','Verenigd Koninkrijk','GB',99.6)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('y-mee','55441','Verenigde Staten','US',97.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('yozos','77532','Verenigde Staten','US',99.3)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('yugblad','NG103FW','Verenigd Koninkrijk','GB',71.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('zeitreiseoldenburg2013','26125','Duitsland','DE',59.0)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('zeitsprung-klassiker','50170','Duitsland','DE',98.4)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('zirtaky','79312','Duitsland','DE',99.6)
INSERT Users (Username,Postalcode,Location,Country,Rating) VALUES ('zorak_zorani','CH454JA','Verenigd Koninkrijk','GB',78.0)